## open_data.R
## Preparation step: run this once at the start of a session, before any
## downstream burden-estimation script (e.g. age_strat_comorb_burden.R).
## It loads every library, shared function file, and data object those
## scripts assume already exist in the environment.

## 1. Libraries --------------------------------------------------------
## Core data wrangling / analysis
library(dplyr)
library(tidyr)
library(tibble)
library(data.table)

## Sampling (LHS Monte Carlo draws)
library(lhs)

## Reading external data
library(readxl)

## Plotting (used by age_strat_comorb_burden.R and by the plotting helpers
## in Functions/BurdenFunctions_v2.R)
library(ggplot2)
library(scales)
library(ggthemes)
library(paletteer)
library(tidyterra)

## 2. Shared function definitions ---------------------------------------
source("Functions/age_strat_subinf_func_final.R")
source("Functions/BurdenFunctions_v2.R")

## 3. LHS parameter draws + hospitalisation/mortality/life-expectancy samples
##    (generated by lhs_samples.R and saved out to MainData/)
load("MainData/le_sample.RData")
load("MainData/nh_fatal_sample.RData")
load("MainData/fatal_sample.RData")
load("MainData/hosp_sample.RData")
load("MainData/lhs_sample_young.RData")
load("MainData/lhs_old.RData")

## 4. FOI and infection burden data --------------------------------------
load("MainData/allfoi_s1.RData")
load("MainData/all_age_infection.RData")
load("MainData/combined_burden_shrink.RData")

## 5. Comorbidity data ----------------------------------------------------
load("MainData/rr_hosp_model.RData")
# TODO: copy bg_count_dist_wide.RData into MainData/ from
# ../CHIK_MORBID/CHIK_MORBID/01_Data/calc_outputs/ before running this line
load("MainData/bg_count_dist_wide.RData")

## 6. Drop countries handled by a separate pipeline (USA, China) ----------
all_age_infection <- all_age_infection[!all_age_infection$country %in% c("United States of America", "China" ),]

## 7. Collapse the 18 five-year `mid` columns into the 9 ten-year
##    `tot_infec_med_group1..9` bands used by downstream scripts
all_age_infection$tot_infec_med_group1 <- rowSums(all_age_infection[, paste0("mid", 1:3)], na.rm = TRUE)
all_age_infection$tot_infec_med_group2 <- rowSums(all_age_infection[, paste0("mid", 4:5)], na.rm = TRUE)
all_age_infection$tot_infec_med_group3 <- rowSums(all_age_infection[, paste0("mid", 6:7)], na.rm = TRUE)
all_age_infection$tot_infec_med_group4 <- rowSums(all_age_infection[, paste0("mid", 8:9)], na.rm = TRUE)
all_age_infection$tot_infec_med_group5 <- rowSums(all_age_infection[, paste0("mid", 10:11)], na.rm = TRUE)
all_age_infection$tot_infec_med_group6 <- rowSums(all_age_infection[, paste0("mid", 12:13)], na.rm = TRUE)
all_age_infection$tot_infec_med_group7 <- rowSums(all_age_infection[, paste0("mid", 14:15)], na.rm = TRUE)
all_age_infection$tot_infec_med_group8 <- rowSums(all_age_infection[, paste0("mid", 16:17)], na.rm = TRUE)
all_age_infection$tot_infec_med_group9 <- rowSums(all_age_infection[, paste0("mid", 18)], na.rm = TRUE)

## 8. Summarise combined_burden to one row per country (total infections,
##    iso3, continent, population), then attach total population onto
##    all_age_infection
infection_focal <- combined_burden %>% group_by(country) %>%
  summarise(tot_infec_med  = sum(med_inf),
            tot_infec_lo   = sum(lo_inf),
            tot_infec_hi   = sum(hi_inf),
            iso3           = first(iso3),
            country        = first(country),
            continent      = first(continent),
            tot_pop        = sum(tot_pop)
  ) %>%
  as.data.frame()
tot_pop <- infection_focal %>% dplyr::select(country, tot_pop)
all_age_infection <- all_age_infection %>% left_join(tot_pop, by = "country")
all_age_infection <- all_age_infection[,-2]

## 9. Attach continent from the region-classification lookup
region_classification <- read_excel("MainData/region_classification.xlsx",
                                    sheet = "region")
continent <- region_classification$continent
all_age_infection <- cbind(continent, all_age_infection)
colnames(all_age_infection)[1] <- "continent"
